## Usando a bibloteca tabula

### instalação

In [17]:
#!pip install tabula-py
#!pip install openpyxl
#!pip install jpype1

Requirement already satisfied: jpype1 in c:\users\gustavocamargo\appdata\local\anaconda3\lib\site-packages (1.5.1)
Requirement already satisfied: packaging in c:\users\gustavocamargo\appdata\local\anaconda3\lib\site-packages (from jpype1) (23.2)

In [7]:
!pip show tabula-py

Name: tabula-py
Version: 2.10.0
Summary: Simple wrapper for tabula-java, read tables from PDF into DataFrame
Home-page:
Author:
Author-email: Aki Ariga <chezou@gmail.com>
License: The MIT License (MIT)
Copyright (c) 2016 Michiaki Ariga

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Location: C:\Users\gustavocamargo\AppData\Local\anaconda3\Lib\site-packages
Requires: distro, numpy, pandas
Required-by:

### Extração da tabela

In [19]:
import os

# Configurando a JVM manualmente
os.environ['JAVA_HOME'] = r"C:\Program Files\Java\jre1.8.0_441"
os.environ['PATH'] += os.pathsep + os.path.join(os.environ['JAVA_HOME'], 'bin')

In [114]:
import tabula
import pandas as pd

arquivo_pdf = "ranking-abras-2024-completo.pdf"
tabelas = tabula.read_pdf(
    arquivo_pdf,
    pages='2-38',
    multiple_tables=True,
    lattice=False,
    stream=True,
    pandas_options={"header": None}
)

In [115]:
colunas = ["Ranking 2024", "Ranking 2023", "Razão Social", "Sede", "Faturamento (R$)"]

tabelas_corrigidas = []
for tabela in tabelas:
    if tabela.shape[1] == 5:
        tabela.columns = colunas
        tabelas_corrigidas.append(tabela)

df_final = pd.concat(tabelas_corrigidas, ignore_index=True)

In [116]:
df_final.head()

,Ranking 2024,Ranking 2023,Razão Social,Sede,Faturamento (R$)
0,1 1,NaN,CARREFOUR COMÉRCIO E INDÚSTRIA LTDA.,SP,115.458.000.000
1,2 2,NaN,ASSAÍ ATACADISTA,SP,72.785.000.000
2,3 3,NaN,MATEUS SUPERMERCADOS S.A.,MA,30.245.569.000
3,4 4,NaN,GPA,SP,20.617.000.000
4,5 5,NaN,SUPERMERCADOS BH COMÉRCIO DE ALIMENTOS S.A.,MG,17.388.297.482

In [117]:
df_final.tail()

,Ranking 2024,Ranking 2023,Razão Social,Sede,Faturamento (R$)
1284,1.245,Nova,MERCEARIA KAWAMOTO LTDA ME,SP,144.000
1285,1.246,1.237,GAP4 SUPERMERCADOS LTDA,SP,120.000
1286,1.247,Nova,COMÉRCIO DE ALIMENTOS DAHMER LTDA ME,RS,120.000
1287,1.248,1.245,COMERCIAL DONA LIDIA LTDA,SC,113.525
1288,1.249,1.247,JOÃO N LIMA MICROEMPRESA,CE,100.000

In [223]:
df = df_final.copy()

In [225]:
df.head(100)

,Ranking 2024,Ranking 2023,Razão Social,Sede,Faturamento (R$)
0,1 1,NaN,CARREFOUR COMÉRCIO E INDÚSTRIA LTDA.,SP,115.458.000.000
1,2 2,NaN,ASSAÍ ATACADISTA,SP,72.785.000.000
2,3 3,NaN,MATEUS SUPERMERCADOS S.A.,MA,30.245.569.000
3,4 4,NaN,GPA,SP,20.617.000.000
4,5 5,NaN,SUPERMERCADOS BH COMÉRCIO DE ALIMENTOS S.A.,MG,17.388.297.482
...,...,...,...,...,...
95,89,80,SUPERMERCADO VIANENSE LTDA.,RJ,842.013.120
96,90,84,SUPERMERCADO GUANABARA S.A.,RS,835.165.135
97,91,83,ANDORINHA SUPERMERCADO LTDA.,SP,829.434.012
98,92,81,SUPERMERCADO ARCHER S.A.,SC,825.872.853
99,93,90,MN SUPERMERCADOS LTDA.,MG,817.137.842

### Resolvendo alguns problemas

In [228]:
# Garante que são strings
df[['Ranking 24', 'Ranking 23']] = df['Ranking 2024'].str.split(' ', expand=True, n=1)

df

,Ranking 2024,Ranking 2023,Razão Social,Sede,Faturamento (R$),Ranking 24,Ranking 23
0,1 1,NaN,CARREFOUR COMÉRCIO E INDÚSTRIA LTDA.,SP,115.458.000.000,1,1
1,2 2,NaN,ASSAÍ ATACADISTA,SP,72.785.000.000,2,2
2,3 3,NaN,MATEUS SUPERMERCADOS S.A.,MA,30.245.569.000,3,3
3,4 4,NaN,GPA,SP,20.617.000.000,4,4
4,5 5,NaN,SUPERMERCADOS BH COMÉRCIO DE ALIMENTOS S.A.,MG,17.388.297.482,5,5
...,...,...,...,...,...,...,...
1284,1.245,Nova,MERCEARIA KAWAMOTO LTDA ME,SP,144.000,NaN,NaN
1285,1.246,1.237,GAP4 SUPERMERCADOS LTDA,SP,120.000,NaN,NaN
1286,1.247,Nova,COMÉRCIO DE ALIMENTOS DAHMER LTDA ME,RS,120.000,NaN,NaN
1287,1.248,1.245,COMERCIAL DONA LIDIA LTDA,SC,113.525,NaN,NaN
1288,1.249,1.247,JOÃO N LIMA MICROEMPRESA,CE,100.000,NaN,NaN

In [230]:
# Preenche valores NaN em 'Ranking 24' com os valores de 'Ranking 2024'
df['Ranking 24'] = df['Ranking 24'].fillna(df['Ranking 2024'])

# Preenche valores NaN em 'Ranking 23' com os valores de 'Ranking 2023'
df['Ranking 23'] = df['Ranking 23'].fillna(df['Ranking 2023'])

# Preenche valores NaN em 'Razão Social' com os valores de 'Ranking 2023'
df['Razão Social'] = df['Razão Social'].fillna(df['Ranking 2023'])

df

,Ranking 2024,Ranking 2023,Razão Social,Sede,Faturamento (R$),Ranking 24,Ranking 23
0,1 1,NaN,CARREFOUR COMÉRCIO E INDÚSTRIA LTDA.,SP,115.458.000.000,1,1
1,2 2,NaN,ASSAÍ ATACADISTA,SP,72.785.000.000,2,2
2,3 3,NaN,MATEUS SUPERMERCADOS S.A.,MA,30.245.569.000,3,3
3,4 4,NaN,GPA,SP,20.617.000.000,4,4
4,5 5,NaN,SUPERMERCADOS BH COMÉRCIO DE ALIMENTOS S.A.,MG,17.388.297.482,5,5
...,...,...,...,...,...,...,...
1284,1.245,Nova,MERCEARIA KAWAMOTO LTDA ME,SP,144.000,1.245,Nova
1285,1.246,1.237,GAP4 SUPERMERCADOS LTDA,SP,120.000,1.246,1.237
1286,1.247,Nova,COMÉRCIO DE ALIMENTOS DAHMER LTDA ME,RS,120.000,1.247,Nova
1287,1.248,1.245,COMERCIAL DONA LIDIA LTDA,SC,113.525,1.248,1.245
1288,1.249,1.247,JOÃO N LIMA MICROEMPRESA,CE,100.000,1.249,1.247

In [232]:
df.iloc[100:120]

,Ranking 2024,Ranking 2023,Razão Social,Sede,Faturamento (R$),Ranking 24,Ranking 23
100,94,79,COMERCIAL OSWALDO CRUZ LTDA.,SP,805.920.933,94,79
101,95,86,S PIRES COMÉRCIO DE ALIMENTOS LTDA.,MS,792.873.523,95,86
102,96,87,SUPERMERCADO IQUEGAMI LTDA.,SP,786.907.888,96,87
103,97,89,BARÃO ESPECIALIDADES & DISTRIBUIDORA DE ALIMEN...,GO,730.557.446,97,89
104,2024 2023,Razão Social,Razão Social,Sede,Faturamento (R$),2024,2023
105,98 Nova,ECONOMICO COMÉRCIO DE ALIMENTOS LTDA.,ECONOMICO COMÉRCIO DE ALIMENTOS LTDA.,PA,725.337.644,98,Nova
106,99 Nova,NOSSO ATACAREJO COMÉRCIO DE GENÊROS ALIMENTÍCI...,NOSSO ATACAREJO COMÉRCIO DE GENÊROS ALIMENTÍCI...,RN,703.951.081,99,Nova
107,100 Nova,SUPERMERCADO PEPÃO LTDA.,SUPERMERCADO PEPÃO LTDA.,RJ,700.000.000,100,Nova
108,Total 100 Maiores,NaN,NaN,NaN,517.409.687.171,Total,100 Maiores
109,101 Nova,HIPER COMPRAS ATACADO E DISTRIBUIÇÃO DE ALIMENTOS,HIPER COMPRAS ATACADO E DISTRIBUIÇÃO DE ALIMENTOS,BA,688.013.496,101,Nova
110,102 93,SANCHES & VECCHIATE LTDA.,SANCHES & VECCHIATE LTDA.,PR,686.642.000,102,93
111,103 97,MAGLIONI RIBEIRO E CIA. LTDA.,MAGLIONI RIBEIRO E CIA. LTDA.,MG,686.360.311,103,97
112,104 94,NOVO MIX ATACADO DE ALIMENTOS LTDA.,NOVO MIX ATACADO DE ALIMENTOS LTDA.,BA,682.399.309,104,94
113,105 119,SUPERVIZA SUPERMERCADOS LTDA.,SUPERVIZA SUPERMERCADOS LTDA.,SC,679.119.061,105,119
114,106 Nova,RF ATACADO DE ALIMENTOS S.A.,RF ATACADO DE ALIMENTOS S.A.,BA,661.824.054,106,Nova
115,107 101,BOM VIZINHO DISTRIBUIDORA DE ALIMENTOS LTDA.,BOM VIZINHO DISTRIBUIDORA DE ALIMENTOS LTDA.,CE,659.968.036,107,101
116,108 107,SUPERMERCADO DELTA MAX LTDA.,SUPERMERCADO DELTA MAX LTDA.,SP,624.583.238,108,107
117,109 91,UNISUPER - REDE UNIÃO GAUCHA DE SUP. ATAC. E D...,UNISUPER - REDE UNIÃO GAUCHA DE SUP. ATAC. E D...,RS,620.886.048,109,91
118,110 95,RWR LOGISTICA E DISTRIBUIÇÃO LTDA.,RWR LOGISTICA E DISTRIBUIÇÃO LTDA.,SC,616.138.052,110,95
119,111 103,QUARTETTO SUPERMERCADOS LTDA.,QUARTETTO SUPERMERCADOS LTDA.,TO,613.041.416,111,103

In [234]:
df = df.drop(columns=['Ranking 2024', 'Ranking 2023'])

In [236]:
# Renomeando as colunas
df = df.rename(columns={
    'Ranking 24': 'Ranking 2024',
    'Ranking 23': 'Ranking 2023',
    'Razão Social': 'Nome da Empresa',
    'Sede': 'Sede',
    'Faturamento (R$)': 'Faturamento Total (R$)'
})

# Reordenando as colunas (coloque na ordem que desejar)
df = df[['Ranking 2024', 'Ranking 2023', 'Nome da Empresa', 'Sede', 'Faturamento Total (R$)']]

In [244]:
# Remove as linhas que contêm a palavra "Total" em qualquer coluna
df = df[~df.apply(lambda row: row.astype(str).str.contains('Total', case=False).any(), axis=1)]
df = df[~df.apply(lambda row: row.astype(str).str.contains('2024', case=False).any(), axis=1)]

In [246]:
df.head()

,Ranking 2024,Ranking 2023,Nome da Empresa,Sede,Faturamento Total (R$)
0,1,1,CARREFOUR COMÉRCIO E INDÚSTRIA LTDA.,SP,115.458.000.000
1,2,2,ASSAÍ ATACADISTA,SP,72.785.000.000
2,3,3,MATEUS SUPERMERCADOS S.A.,MA,30.245.569.000
3,4,4,GPA,SP,20.617.000.000
4,5,5,SUPERMERCADOS BH COMÉRCIO DE ALIMENTOS S.A.,MG,17.388.297.482

In [248]:
df.to_excel('tabela_extraida.xlsx')